### ISSUE TITLE
Parameter presets?

### ISSUE THREAD

**Issue by UnquietCode** [PWhiddy/fluid#1]
Hi there. The videos you have rendered look great, but I am having a hard time adjusting the input parameters to get anywhere close to those runs. Would it be possible to add some of the parameters used in the videos to the Readme or another file?

FYI: I have parameterized the inputs in a fork to allow them to be passed via the command line, and I will be glad to send back those changes after I can confirm that they are working well with some presets.

**Comment by PWhiddy** [comment]
Hi @UnquietCode !
Which parameters did you adjust?
To produce initial conditions like in the screenshots, I believe both the wavey_impluses at 
https://github.com/animallabs/Fat-Clouds/blob/master/fluid.cu#L613
should be commented out, and the soft_impulses at
https://github.com/animallabs/Fat-Clouds/blob/master/fluid.cu#L413
should be uncommented. If that doesn't start to look right let me know and I will try it myself.
To make those different modes configurable via external parameters, it would just be a matter of adding a couple branches. If you have some useful changes, please do make a pull request!

**Comment by UnquietCode** [comment]
Thank you very much! That was all that was needed. I was able to get a single impulse rendering with parameterized colors and other settings. I will send back some changes soon.

**Comment by UnquietCode** [comment]
Thanks again for your help. Here are some random permutations that I have generated to test the parameterized version (for your entertainment).

https://drive.google.com/drive/folders/11z8hnIYrhLf4PELbktVdluYJmlNpnbTm?usp=sharing

**Comment by PWhiddy** [comment]
Those are awesome! Thanks for sharing.
